### ISSUE TITLE
#RealTalk

### ISSUE THREAD

**Issue by mikeumus** [bevry-archive/meta#7]
Read this post on Zapier's blog about the company Hudl using being "Respectfully Blunt" as a form of eliminating waste. I know were an open-source team and not a traditional company but I still say we adopt this as a policy so that no time is wasted beating around the bush. This parallels the idea of having daily catchup hangouts as well, being that we need to to do things now and not later and also the more we're in communication the healthier our org is. 

https://zapier.com/blog/real-talk-hudl-company-culture/

**Comment by balupton** [comment]
There's a word for Respectfully Blunt, it's kurt.

Honestly, I think while it is easy to be blunt, and it is more efficient, the damage done to people's personalities makes it ineffective.

The book "How to win friends and influence people" written about 100 years ago, still rings true for this exact point today. It covers countless examples where putting in a little bit more effort, while less efficient, is tremendously more effective — in ways that couldn't even be imagined.

I'd prefer lasting change, than quick change, any day.

Again though, it's a thing that we can use with judgement. I think between myself and yourself, we can be blunt, because our minds don't care and we already have deep rapport and respect for each other that we know won't go unaltered. However, respectfully blunt with a stranger whom I don't have deep rapport, or even someone I do have deep rapport but is of a feeling personality (i.e. my wife), is never a good idea — it alienates them — a quick 30 second kurt statement, can quickly turn into a week long bitterness, or even a falling out, especially in open-source — of which it's occured to me.

This isn't saying we shouldn't be concise. Booyeah for conciseness. Let's just make sure to be politely concise, rather than respectfully blunt (aka kurt).

For saving time while being politely concise all the time, the solution to that is abstraction, like a FAQ, or any resource that people can be pointed to, rather than having to reply each time.

**Comment by balupton** [comment]
Going to close, as this is something I've taken great care to foster within Bevry over the years, which foundations are evident in the essence of our support guidelines: http://bevry.me/learn/bevry-support-guidelines

**Comment by mikeumus** [comment]
So you've read the book too. Three generations of my family has read that book and it's very foundational for me as well. I think the main take away of #Realtalk is to be clear with people and don't tell someone something is fine when it's really not and then it slips, but mix in a little HTWFAIP to deliver that message correctly/effectively/politely.

**Comment by balupton** [comment]
@mikeumus +1
